apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ DEPLOYMENT_NAME }}"
  labels:
    app: nginx 
  annotations:
    latencySoftConstraint: "1"
    latencyHardConstraint: "60"
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        latencySoftConstraint: "1"
        latencyHardConstraint: "60"
    spec:
      containers:
      - name: nginx
        image: nginx:latest  
        ports:
        - containerPort: 80  
        resources:
          requests:
            memory: "64Mi"   # Esempio di richiesta di 64 megabyte di memoria
            cpu: "250m"      # Esempio di richiesta di 250 millicpu (0.25 CPU)

